fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    archive: https://github.com/voxpupuli/puppet-archive
    concat:  https://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    ngrok: "#{source_dir}"
